language: swift

osx_image: xcode14.2
env:
  matrix:
    - TEST_SDK=iphonesimulator16.2 OS=16.2 NAME='iPhone 14 Pro Max'
    - TEST_SDK=iphonesimulator16.2 OS=16.2 NAME='iPhone 8'
branches:
  only:
    - master
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project SwiftyLib.xcodeproj -scheme SwiftyLib -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
